USE leafdb; 

CREATE TABLE IF NOT EXISTS `tb_vendas` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idUsuario` INT NOT NULL,
    `idProduto` INT NOT NULL,
    `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT `idUsuario` FOREIGN KEY (`idUsuario`) REFERENCES `tb_usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `idProduto` FOREIGN KEY (`idProduto`) REFERENCES `tb_produtos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

SHOW TABLES; 